name: ai-character-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - groq
      - langchain
      - langchain-groq
      - langchain-community
      - langchain-huggingface
      - faiss-cpu
      - python-dotenv
      - pandas
      - jinja2
      - transformers
      - torch
      - python-multipart
      - requests
      - pytest
      - pydantic-settings
